version: "3.9"

services:
  laravel:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ../src/laravel/:/app

  nextjs:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ../src/client:/app 
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - 33006:33006
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
      
volumes:
  mysql-volume:
